### Realizar las importaciones necesarias para la limpieza

In [34]:
import pandas as pd
import numpy as np
import datetime

### Leer y mostrar los primeros registros del csv para estudiar su estructura

In [35]:
data = pd.read_csv('mock_becas.csv')
data.head()

,fecha,estado,municipio,parroquia,sector,nombres_completos,cedula,genero,fecha_nacimiento,direccion,...,fuente_ingreso,trabaja,dificultades,apoyos,banco,tipo_cuenta,numero_cuenta,servicio_comunitario,horarios,ubicacion_universidad
0,2026-08-01,Zulia,ROSARIO DE PERIJA,EL ROSARIO,Centro,Ana Maria Gonzalez,28123456,F,2007-04-15,"Av. 5, casa 12, sector Centro",...,INFORMAL,NO,"utiles, transporte","material_escolar, transporte_apoyo",Banco de Venezuela,Ahorro,1020000012345678901,SI,"Lunes y miercoles, 2:00 pm a 5:00 pm",La Villa
1,2026-08-03,Zulia,ROSARIO DE PERIJA,SIXTO ZAMBRANO,La Esperanza,Carlos Eduardo Perez,27987654,M,2006-11-02,"Calle 8, barrio La Esperanza",...,INFORMAL,SI,"matricula, tecnologia","ayuda_economica, beca",Banesco,Corriente,1340000098765432109,NO,NaN,foraneo
2,2026-08-05,Zulia,ROSARIO DE PERIJA,DONALDO GARCÍA,Las Palmeras,Daniela Sofia Rios,30111222,F,2008-08-27,"Sector Las Palmeras, calle principal",...,FORMAL,NO,"alimentacion, hospedaje","alimentacion_apoyo, ayuda_economica",Banco Mercantil,Ahorro,1050000111222333344,SI,Sabados en la manana,La Villa
3,2026-08-07,Zulia,ROSARIO DE PERIJA,EL ROSARIO,El progreso,Jose Miguel Martinez,27654321,M,2005-02-19,"Carretera principal, casa 45",...,FORMAL,SI,"transporte, tecnologia, utiles","transporte_apoyo, empleo",Banco Occidental de Descuento,Corriente,1160000987654321012,SI,Viernes despues de las 6:00 pm,foraneo
4,2026-08-10,Zulia,ROSARIO DE PERIJA,SIXTO ZAMBRANO,San Miguel,Valentina Isabel Castillo,29333444,F,2007-12-10,"Urbanizacion San Miguel, bloque 3",...,INFORMAL,NO,"matricula, alimentacion","beca, material_escolar, alimentacion_apoyo",Banco Nacional de Credito,Ahorro,1910000444555666677,NO,NaN,La Villa

### Realizar los reemplazos necesarios para crear graficos eficientemente

In [36]:
data['ubicacion_universidad'] = data['ubicacion_universidad'].replace({'La Villa': 'Villa del Rosario', 'foraneo':'Maracaibo'}, inplace=True)
data['servicio_comunitario'] = data['servicio_comunitario'].replace({'SI':1, 'NO':0}, inplace=True)
data['trabaja'] = data['trabaja'].replace({'SI':1, 'NO':0}, inplace=True)
data.head()

C:\Users\Hi\AppData\Local\Temp\ipykernel_24960\2121831327.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['ubicacion_universidad'] = data['ubicacion_universidad'].replace({'La Villa': 'Villa del Rosario', 'foraneo':'Maracaibo'}, inplace=True)
C:\Users\Hi\AppData\Local\Temp\ipykernel_24960\2121831327.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['servicio_comunitario'] = data['servicio_comunitario'].replace({'SI':1, 'NO':0}, inplace=True)
C:\Users\Hi\AppData\Local\Temp\ipykernel_24960\2121831327.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['trabaja'] = data['trabaja'].replace({'SI':1, 'NO':0}, inplace=True)

,fecha,estado,municipio,parroquia,sector,nombres_completos,cedula,genero,fecha_nacimiento,direccion,...,fuente_ingreso,trabaja,dificultades,apoyos,banco,tipo_cuenta,numero_cuenta,servicio_comunitario,horarios,ubicacion_universidad
0,2026-08-01,Zulia,ROSARIO DE PERIJA,EL ROSARIO,Centro,Ana Maria Gonzalez,28123456,F,2007-04-15,"Av. 5, casa 12, sector Centro",...,INFORMAL,0,"utiles, transporte","material_escolar, transporte_apoyo",Banco de Venezuela,Ahorro,1020000012345678901,1,"Lunes y miercoles, 2:00 pm a 5:00 pm",Villa del Rosario
1,2026-08-03,Zulia,ROSARIO DE PERIJA,SIXTO ZAMBRANO,La Esperanza,Carlos Eduardo Perez,27987654,M,2006-11-02,"Calle 8, barrio La Esperanza",...,INFORMAL,1,"matricula, tecnologia","ayuda_economica, beca",Banesco,Corriente,1340000098765432109,0,NaN,Maracaibo
2,2026-08-05,Zulia,ROSARIO DE PERIJA,DONALDO GARCÍA,Las Palmeras,Daniela Sofia Rios,30111222,F,2008-08-27,"Sector Las Palmeras, calle principal",...,FORMAL,0,"alimentacion, hospedaje","alimentacion_apoyo, ayuda_economica",Banco Mercantil,Ahorro,1050000111222333344,1,Sabados en la manana,Villa del Rosario
3,2026-08-07,Zulia,ROSARIO DE PERIJA,EL ROSARIO,El progreso,Jose Miguel Martinez,27654321,M,2005-02-19,"Carretera principal, casa 45",...,FORMAL,1,"transporte, tecnologia, utiles","transporte_apoyo, empleo",Banco Occidental de Descuento,Corriente,1160000987654321012,1,Viernes despues de las 6:00 pm,Maracaibo
4,2026-08-10,Zulia,ROSARIO DE PERIJA,SIXTO ZAMBRANO,San Miguel,Valentina Isabel Castillo,29333444,F,2007-12-10,"Urbanizacion San Miguel, bloque 3",...,INFORMAL,0,"matricula, alimentacion","beca, material_escolar, alimentacion_apoyo",Banco Nacional de Credito,Ahorro,1910000444555666677,0,NaN,Villa del Rosario

### Calcular la fecha de nacimiento para poder categorizar a los estudiantes en menores o mayores de edad

In [37]:
data['fecha_nacimiento'] = pd.to_datetime(data['fecha_nacimiento'], errors='coerce')
data['edad'] = (datetime.datetime.now() - data['fecha_nacimiento']).dt.days // 365
# Creación de la columna "edad_categorica" basada en la edad (Binning)
# limite = 18
"""data["categoria_edad"] = np.where(
    data["edad"] < limite,
    "Menor de 18 años",
    "Mayor o igual a 18 años"
)"""
# Creación de la columna "edad_categorica" usando pd.cut() para categorizar la edad en "Menor de edad" y "Mayor de edad"
bins_edad = [-np.inf, 17, np.inf]
labels_edad = ['Menor de edad', 'Mayor de edad']
data['edad_categorica'] = pd.cut(data['edad'], bins=bins_edad, labels=labels_edad, include_lowest=True)
data.head()

,fecha,estado,municipio,parroquia,sector,nombres_completos,cedula,genero,fecha_nacimiento,direccion,...,dificultades,apoyos,banco,tipo_cuenta,numero_cuenta,servicio_comunitario,horarios,ubicacion_universidad,edad,edad_categorica
0,2026-08-01,Zulia,ROSARIO DE PERIJA,EL ROSARIO,Centro,Ana Maria Gonzalez,28123456,F,2007-04-15,"Av. 5, casa 12, sector Centro",...,"utiles, transporte","material_escolar, transporte_apoyo",Banco de Venezuela,Ahorro,1020000012345678901,1,"Lunes y miercoles, 2:00 pm a 5:00 pm",Villa del Rosario,19,Mayor de edad
1,2026-08-03,Zulia,ROSARIO DE PERIJA,SIXTO ZAMBRANO,La Esperanza,Carlos Eduardo Perez,27987654,M,2006-11-02,"Calle 8, barrio La Esperanza",...,"matricula, tecnologia","ayuda_economica, beca",Banesco,Corriente,1340000098765432109,0,NaN,Maracaibo,19,Mayor de edad
2,2026-08-05,Zulia,ROSARIO DE PERIJA,DONALDO GARCÍA,Las Palmeras,Daniela Sofia Rios,30111222,F,2008-08-27,"Sector Las Palmeras, calle principal",...,"alimentacion, hospedaje","alimentacion_apoyo, ayuda_economica",Banco Mercantil,Ahorro,1050000111222333344,1,Sabados en la manana,Villa del Rosario,18,Mayor de edad
3,2026-08-07,Zulia,ROSARIO DE PERIJA,EL ROSARIO,El progreso,Jose Miguel Martinez,27654321,M,2005-02-19,"Carretera principal, casa 45",...,"transporte, tecnologia, utiles","transporte_apoyo, empleo",Banco Occidental de Descuento,Corriente,1160000987654321012,1,Viernes despues de las 6:00 pm,Maracaibo,21,Mayor de edad
4,2026-08-10,Zulia,ROSARIO DE PERIJA,SIXTO ZAMBRANO,San Miguel,Valentina Isabel Castillo,29333444,F,2007-12-10,"Urbanizacion San Miguel, bloque 3",...,"matricula, alimentacion","beca, material_escolar, alimentacion_apoyo",Banco Nacional de Credito,Ahorro,1910000444555666677,0,NaN,Villa del Rosario,18,Mayor de edad

### Finalmente, se exporta el csv con las columnas necesarias para construir el dashboard con las metricas solicitadas.

In [38]:
data.to_csv('mock_becas_limpio.csv', index=False)