### Realizar las importaciones necesarias para la limpieza

In [15]:
import pandas as pd
import numpy as np
import datetime

### Leer y mostrar los primeros registros del csv para estudiar su estructura

In [16]:
data = pd.read_csv('mock_becas.csv')
data.head()

,fecha,estado,municipio,parroquia,sector,nombres_completos,cedula,genero,fecha_nacimiento,direccion,...,fuente_ingreso,trabaja,dificultades,apoyos,banco,tipo_cuenta,numero_cuenta,servicio_comunitario,horarios,ubicacion_universidad
0,2026-08-16,Zulia,ROSARIO DE PERIJA,DONALDO GARCÍA,Villa del Rosario,Valentina Diego Romero Martinez,27678312,F,2006-09-16,"Calle 11, Villa del Rosario, casa 10",...,FORMAL,NO,utiles,"material_escolar, beca, empleo",Banco del Tesoro,Ahorro,1630000674469291241,SI,Martes y jueves,Maracaibo
1,2026-08-10,Zulia,ROSARIO DE PERIJA,DONALDO GARCÍA,San Miguel,Marta Fernando Mendoza Gomez,31210094,M,2007-10-25,"Calle 1, San Miguel, casa 22",...,FORMAL,NO,"transporte, hospedaje, alimentacion","alimentacion_apoyo, material_escolar",Banco Occidental de Descuento,Corriente,1160000614363134552,SI,Lunes y miercoles,La Villa
2,2026-08-18,Zulia,ROSARIO DE PERIJA,EL ROSARIO,Corito,Ana Camila Lopez Romero,30301647,M,2007-10-05,"Calle 2, Corito, casa 11",...,NINGUNO,NO,"alimentacion, hospedaje, tecnologia","alimentacion_apoyo, ayuda_economica",Banco Mercantil,Corriente,1050000235919541989,SI,Sabados en la manana,foraneo
3,2026-08-22,Zulia,ROSARIO DE PERIJA,EL ROSARIO,El Carmen,Gabriel Lucia Diaz Flores,31081450,F,2010-02-17,"Calle 13, El Carmen, casa 31",...,INFORMAL,NO,"utiles, matricula, alimentacion","transporte_apoyo, alimentacion_apoyo",BBVA Provincial,Corriente,1080000242434175978,NO,NaN,La Villa
4,2026-08-08,Zulia,ROSARIO DE PERIJA,EL ROSARIO,San Miguel,Diego Elena Gonzalez Ramirez,26145713,M,2007-11-27,"Calle 4, San Miguel, casa 12",...,INFORMAL,NO,hospedaje,transporte_apoyo,Banco del Tesoro,Corriente,1630000217247997637,NO,NaN,La Villa

### Realizar los reemplazos necesarios para crear graficos eficientemente

In [17]:
data['ubicacion_universidad'] = data['ubicacion_universidad'].replace({'La Villa': 'La Villa Del Rosario', 'foraneo':'Maracaibo'})
data['servicio_comunitario'] = data['servicio_comunitario'].replace({'SI':'Acepto', 'NO':'No acepto'})
data['trabaja'] = data['trabaja'].replace({'SI':'Trabaja', 'NO':'No Trabaja'})
data.head()

,fecha,estado,municipio,parroquia,sector,nombres_completos,cedula,genero,fecha_nacimiento,direccion,...,fuente_ingreso,trabaja,dificultades,apoyos,banco,tipo_cuenta,numero_cuenta,servicio_comunitario,horarios,ubicacion_universidad
0,2026-08-16,Zulia,ROSARIO DE PERIJA,DONALDO GARCÍA,Villa del Rosario,Valentina Diego Romero Martinez,27678312,F,2006-09-16,"Calle 11, Villa del Rosario, casa 10",...,FORMAL,No Trabaja,utiles,"material_escolar, beca, empleo",Banco del Tesoro,Ahorro,1630000674469291241,Acepto,Martes y jueves,Maracaibo
1,2026-08-10,Zulia,ROSARIO DE PERIJA,DONALDO GARCÍA,San Miguel,Marta Fernando Mendoza Gomez,31210094,M,2007-10-25,"Calle 1, San Miguel, casa 22",...,FORMAL,No Trabaja,"transporte, hospedaje, alimentacion","alimentacion_apoyo, material_escolar",Banco Occidental de Descuento,Corriente,1160000614363134552,Acepto,Lunes y miercoles,La Villa Del Rosario
2,2026-08-18,Zulia,ROSARIO DE PERIJA,EL ROSARIO,Corito,Ana Camila Lopez Romero,30301647,M,2007-10-05,"Calle 2, Corito, casa 11",...,NINGUNO,No Trabaja,"alimentacion, hospedaje, tecnologia","alimentacion_apoyo, ayuda_economica",Banco Mercantil,Corriente,1050000235919541989,Acepto,Sabados en la manana,Maracaibo
3,2026-08-22,Zulia,ROSARIO DE PERIJA,EL ROSARIO,El Carmen,Gabriel Lucia Diaz Flores,31081450,F,2010-02-17,"Calle 13, El Carmen, casa 31",...,INFORMAL,No Trabaja,"utiles, matricula, alimentacion","transporte_apoyo, alimentacion_apoyo",BBVA Provincial,Corriente,1080000242434175978,No acepto,NaN,La Villa Del Rosario
4,2026-08-08,Zulia,ROSARIO DE PERIJA,EL ROSARIO,San Miguel,Diego Elena Gonzalez Ramirez,26145713,M,2007-11-27,"Calle 4, San Miguel, casa 12",...,INFORMAL,No Trabaja,hospedaje,transporte_apoyo,Banco del Tesoro,Corriente,1630000217247997637,No acepto,NaN,La Villa Del Rosario

### Calcular la fecha de nacimiento para poder categorizar a los estudiantes en menores o mayores de edad

In [18]:
data['fecha_nacimiento'] = pd.to_datetime(data['fecha_nacimiento'], errors='coerce')
data['edad'] = (datetime.datetime.now() - data['fecha_nacimiento']).dt.days // 365
# Creación de la columna "edad_categorica" basada en la edad (Binning)
# limite = 18
"""data["categoria_edad"] = np.where(
    data["edad"] < limite,
    "Menor de 18 años",
    "Mayor o igual a 18 años"
)"""
# Creación de la columna "edad_categorica" usando pd.cut() para categorizar la edad en "Menor de edad" y "Mayor de edad"
bins_edad = [-np.inf, 17, np.inf]
labels_edad = ['Menor de edad', 'Mayor de edad']
data['edad_categorica'] = pd.cut(data['edad'], bins=bins_edad, labels=labels_edad, include_lowest=True)
data.head()

,fecha,estado,municipio,parroquia,sector,nombres_completos,cedula,genero,fecha_nacimiento,direccion,...,dificultades,apoyos,banco,tipo_cuenta,numero_cuenta,servicio_comunitario,horarios,ubicacion_universidad,edad,edad_categorica
0,2026-08-16,Zulia,ROSARIO DE PERIJA,DONALDO GARCÍA,Villa del Rosario,Valentina Diego Romero Martinez,27678312,F,2006-09-16,"Calle 11, Villa del Rosario, casa 10",...,utiles,"material_escolar, beca, empleo",Banco del Tesoro,Ahorro,1630000674469291241,Acepto,Martes y jueves,Maracaibo,19,Mayor de edad
1,2026-08-10,Zulia,ROSARIO DE PERIJA,DONALDO GARCÍA,San Miguel,Marta Fernando Mendoza Gomez,31210094,M,2007-10-25,"Calle 1, San Miguel, casa 22",...,"transporte, hospedaje, alimentacion","alimentacion_apoyo, material_escolar",Banco Occidental de Descuento,Corriente,1160000614363134552,Acepto,Lunes y miercoles,La Villa Del Rosario,18,Mayor de edad
2,2026-08-18,Zulia,ROSARIO DE PERIJA,EL ROSARIO,Corito,Ana Camila Lopez Romero,30301647,M,2007-10-05,"Calle 2, Corito, casa 11",...,"alimentacion, hospedaje, tecnologia","alimentacion_apoyo, ayuda_economica",Banco Mercantil,Corriente,1050000235919541989,Acepto,Sabados en la manana,Maracaibo,18,Mayor de edad
3,2026-08-22,Zulia,ROSARIO DE PERIJA,EL ROSARIO,El Carmen,Gabriel Lucia Diaz Flores,31081450,F,2010-02-17,"Calle 13, El Carmen, casa 31",...,"utiles, matricula, alimentacion","transporte_apoyo, alimentacion_apoyo",BBVA Provincial,Corriente,1080000242434175978,No acepto,NaN,La Villa Del Rosario,16,Menor de edad
4,2026-08-08,Zulia,ROSARIO DE PERIJA,EL ROSARIO,San Miguel,Diego Elena Gonzalez Ramirez,26145713,M,2007-11-27,"Calle 4, San Miguel, casa 12",...,hospedaje,transporte_apoyo,Banco del Tesoro,Corriente,1630000217247997637,No acepto,NaN,La Villa Del Rosario,18,Mayor de edad

### Finalmente, se exporta el csv con las columnas necesarias para construir el dashboard con las metricas solicitadas.

In [19]:
data.to_csv('mock_becas_limpio.csv', index=False)